
[![.github/workflows/main.yml](https://github.com/ARBIJARI3240/DeviceInfo-Android/actions/workflows/main.yml/badge.svg?event=workflow_run)](https://github.com/ARBIJARI3240/DeviceInfo-Android/actions/workflows/main.yml)
